- hosts: all
  tasks:
  - name: Apache latest version installation
    yum:
      name: httpd
      state: latest

  - name: Enable service to start on boot up
    service:
      name: httpd
      state: started
  - name: Create firewall rule for apache service
    firewalld:
      service: http
      zone: public
      permanent: yes
      immediate: yes
      state: enabled
  handlers:
  - name: Restart apache service
    service:
      name: httpd
      state: Restarted

  - name: extractor presents
      ansible.builtin.yum:
        name:
          - unzip
          - tar
        state: present
      become: true
- name: extract archive
      ansible.builtin.unarchive:
        src: "{{ https://www.free-css.com/free-css-templates }}"
        dest: "/var/www/html"